/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.WozniakInterfaces
{
    public class TriggerLLMResponse : Message
    {
        public const string RosMessageName = "wozniak_interfaces/TriggerLLM";

        public string message { get; set; }
        public bool success { get; set; }

        public TriggerLLMResponse()
        {
            this.message = "";
            this.success = false;
        }

        public TriggerLLMResponse(string message, bool success)
        {
            this.message = message;
            this.success = success;
        }
    }
}
