/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Instructions
{
    public class InstructionsLLMResponse : Message
    {
        public const string RosMessageName = "wozniak_interfaces/InstructionsLLM";

        public bool success { get; set; }

        public InstructionsLLMResponse()
        {
            this.success = false;
        }

        public InstructionsLLMResponse(bool success)
        {
            this.success = success;
        }
    }
}
