system_prompt: Nada
tools:
  - type: function
    function:
      name: pick_object
      description: Solicita ao robô que identifique e aponte para um objeto visível na imagem.
      parameters:
        type: object
        properties:
          object:
            type: string
            description: Nome do objeto a ser identificado na imagem
        required:
          - object
